[package]
name = "monkesto"
version = "0.0.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.12", features = ["nightly"] }
leptos_router = { version = "0.8.0", features = ["nightly"] }
axum = { version = "0.8.0" }
tower = {version = "0.4" }
tower-sessions = {version = "0.14" }
tower-sessions-sqlx-store = { version = "0.15", features = ["postgres"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "macros"] }
serde = { version = "1", features = ["derive"] }
console_error_panic_hook = { version = "0.1" }
leptos_meta = { version = "0.8.0" }
tokio = { version = "1", features = ["rt-multi-thread"] }
wasm-bindgen = { version = "=0.2.103" }
chrono = {version = "0.4.42", features = ["serde"]}
bcrypt = {version = "0.17.1"}
rand = {version = "0.9.2"}
dotenvy = "0.15.7"
bitflags = {version = "2.10.0", features = ["serde"]}
chrono-tz = "0.10.4"
base64 = "0.22.1"
postcard = {version = "1.1.3", features = ["alloc"]}
serde_json = "1.0.146"
cuid = {version = "1.3.3"}
clap = "4.5.53"
urlencoding = "2.1.3"
maud = {version = "0.27.0", features = ["axum"]}
webauthn-rs = { version = "0.5.4", features = ["danger-allow-state-serialisation"]}
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tower-http = { version = "0.6.8", features= ["fs"]}
url = "2.5.7"
thiserror = "2.0.17"
uuid = { version = "1.19.0", features = ["v4"]}

[lints.clippy]
unwrap_used = "deny"
