[package]
name = "monkesto"
version = "0.0.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.0", features = ["macros"] }
tower-sessions = {version = "0.15" }
tower-sessions-sqlx-store = { version = "0.15", features = ["postgres"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "macros"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
chrono = {version = "0.4.42", features = ["serde"]}
dotenvy = "0.15.7"
bitflags = {version = "2.10.0", features = ["serde"]}
chrono-tz = "0.10.4"
base64 = "0.22.1"
postcard = {version = "1.1.3", features = ["alloc"]}
cuid = {version = "1.3.3"}
urlencoding = "2.1.3"
maud = {version = "0.27.0", features = ["axum"]}
webauthn-rs = { version = "0.5.4", features = ["danger-allow-state-serialisation"]}
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tower-http = { version = "0.6.8", features= ["fs"]}
url = "2.5.7"
thiserror = "2.0.17"
axum-login = "0.18.0"
serde_json = "1.0.148"
dashmap = "6.1.0"

nutype = { version = "0.6.2", features = ["serde", "regex"] }
regex = "1.12.2"
rand = "0.10.0"
phf = {version = "0.13.1", features = ["macros"]}
webauthn-rs-proto = "0.5.4"
tower-sessions-file-store = "0.2.0"
axum-extra = {version = "0.12.5", features = ["form"]}
rust_decimal = {version = "1.40.0", features = ["macros"]}

[lints.clippy]
unwrap_used = "deny"
