[tasks.default]
alias = "dev"

[tasks.watch-css]
command = "npx"
args = ["tailwindcss", "-i", "./style/input.css", "-o", "./target/site/pkg/monkesto.css", "--watch"]

[tasks.watch-server]
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.dev]
run_task = { name = ["watch-css", "watch-server"], parallel = true }

[tasks.css]
command = "npx"
args = ["tailwindcss", "-i", "./style/input.css", "-o", "./target/site/pkg/monkesto.css", "--minify"]

[tasks.build]
dependencies = ["css"]
command = "cargo"
args = ["build", "--release"]
